name: intercen_app
description: "Intercen Publishers Online Book Store App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  supabase_flutter: ^2.12.0
  cached_network_image: ^3.4.1
  webview_flutter_android: ^4.10.13
  webview_flutter_wkwebview: ^3.24.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  # app_links: ^6.3.0  
  app_links: ^6.0.0   
  image_picker: ^1.0.7
  intl: ^0.19.0
  syncfusion_flutter_pdfviewer: ^26.1.40

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/splashscreen2.png
    - lib/assets/splashscreen3.png
    - lib/assets/splashscreenextra.png
    - lib/assets/googlelogo.jpeg
    - lib/assets/test.png
    - lib/assets/intercenlogo.png
    - lib/assets/barak.png
    - lib/assets/image.png
    - lib/assets/mourning.png
    - lib/assets/whispers.png
    - lib/assets/hitlers.png
    - lib/assets/birds.png
    - lib/assets/pandemic.png
    - lib/assets/maangavu.png
    - lib/assets/egara.jpeg
    # Team images
    - lib/assets/team/barak.jpeg
    - lib/assets/team/chelangatnaomi.jpeg
    - lib/assets/team/bettyatiemo.jpeg
    - lib/assets/team/bahati.jpeg

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: lib/assets/fonts/static/PlayfairDisplay-Regular.ttf
        - asset: lib/assets/fonts/static/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/static/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/static/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/static/PlayfairDisplay-Black.ttf
          weight: 900
